### ISSUE TITLE
fails downloading updates

### ISSUE THREAD

**Issue by cliffordsnow** [eldang/osm_export_import#2]
import.py started failing updates for north-america/us/washington. I found that I needed to strip the trailing slash from the region variable to make it work. Not sure if anyone else is having this problem or if it only in state updates.

In the update_import function I changed the changeset_dir = to the following. It is line 130-133. 
  changeset_dir = (
      "http://download.geofabrik.de/" + region.rstrip("/") + "-updates/000/000/"
  )

**Comment by cliffordsnow** [comment]
I finally realized what is going on. I use tab completion to enter the region on the command line which adds the trailing / on the end. The script works fine if you remove the trailing slash before executing.

**Comment by eldang** [comment]
Sounds like it's worth actually adding that rstrip(), so others don't get tripped up by this.
